project_id = "cvhmlrijuidvrsrzxmfv"

[functions.fetch-youtube-playlist]
verify_jwt = false

[functions.send-new-video-notification]
verify_jwt = false

[functions.cleanup-deleted-accounts]
verify_jwt = false

[functions.send-deletion-email]
verify_jwt = false