// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvhmlrijuidvrsrzxmfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2aG1scmlqdWlkdnJzcnp4bWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNjA5NjEsImV4cCI6MjA2OTczNjk2MX0.N7Atcu_UFXdJr5E5DI3tJNye4tA2DebhESo3Wu17g-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});